### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by Papalo007** [iLoveRat/SkyblockRat#7]
when i follow the tutorial and run it, i get the following error:
1:37:36 PM: Executing 'build'...

Starting Gradle Daemon...
Gradle Daemon started in 1 s 838 ms

> Configure project :
#################################################
         ForgeGradle 2.1-d78e439        
  https://github.com/MinecraftForge/ForgeGradle  
#################################################
               Powered by MCP unknown               
             http://modcoderpack.com             
         by: Searge, ProfMobius, Fesh0r,         
         R4wk, ZeuX, IngisKahn, bspkrs           
#################################################

> Task :deobfCompileDummyTask
> Task :getVersionJson
> Task :extractUserdev
> Task :downloadClient SKIPPED
> Task :downloadServer SKIPPED
> Task :splitServerJar SKIPPED
> Task :mergeJars SKIPPED
> Task :applyBinaryPatches FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.1/userguide/command_line_interface.html#sec:command_line_warnings
4 actionable tasks: 4 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':applyBinaryPatches'.
> java/util/jar/Pack200

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
1:37:46 PM: Execution finished 'build'.

**Comment by iLoveRat** [comment]
i assume u dont need help anymore but if anyone else has this issue to fix:
installed java 13: https://www.oracle.com/java/technologies/javase/jdk13-archive-downloads.html (u need to make an account which is annoying)
run the java 13 exe
search on pc for "advanced system settings" 
in that gui click "envirnment variables" in the bottom right
there should be 2 "new" buttons, click the top one
in the gui put variable name as "JAVA_HOME" and variable value as "C:\Program Files\Java\jdk-13.0.2"
then restart computer and try again
