### ISSUE TITLE
It cant be compiled

### ISSUE THREAD

**Issue by Leg2t** [iLoveRat/SkyblockRat#8]
Please help theres error showing up in intellij. I attached it. My discord is Leg2t#5480
![Screenshot_2023-06-11-22-51-33-35_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/iLoveRat/SkyblockRat/assets/136273114/1fd6faae-6d9d-49c8-8ab5-cd11315ef68a)
![Screenshot_2023-06-11-22-51-39-41_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/iLoveRat/SkyblockRat/assets/136273114/38658d25-ef7f-4c9c-bd32-9213d30590ef)

**Comment by pandaninjas** [comment]
omg it's Leg2t

**Comment by Leg2t** [comment]
Hi panda

**Comment by iLoveRat** [comment]
idk!

**Comment by Leg2t** [comment]
https://github.com/iLoveRat/SkyblockRat/assets/136273114/9d5bce83-a002-44c6-876e-8ddf0cbe24d6

This time i got this error and why the hell u closing this
